CREATE VIEW [test].[swift_mutual_funds] AS
WITH T0 AS
(
SELECT        CAST(EXTREF AS sysname) [Account Number],ORDERDATE,ORDERNO, PORTFOLIO, ORDERTYPE, SECURITIES, UserRef, OrderStatus
FROM            DataHub.SWIFT.fBlotter(DEFAULT, DEFAULT)
WHERE STATUS IN (2,9)
AND		XMITMODE = '928'
AND   ORDERDATE >= '2017-02-15'
AND   ORDERDATE < DATEADD(hh,-1,GETDATE())
AND   ISNULL(OrderStatus,'') <> 'PACK'
AND EXTREF = '00000195344'
), T AS
(
SELECT *
, CASE WHEN CAST(ORDERDATE AS time)> '16:15' THEN DATEADD(hh,10,CAST(CAST(DATEADD(dd,1,ORDERDATE) AS date) as datetime)) ELSE ORDERDATE END OrderDateCalc
 FROM T0
 )
 SELECT *
 FROM T
WHERE CAST(ORDERDATE AS date) >=CAST( DATEADD(dd,-7,GETDATE()) AS date)
AND OrderDateCalc < DATEADD(HH,-1,GETDATE())