CREATE VIEW [dbo].[WhoMe] AS
SELECT SUSER_NAME() AS Nume, 'SUSER_NAME' Foo
UNION ALL
SELECT USER_NAME(),'USER_NAME'
UNION ALL
SELECT SYSTEM_USER,'SYSTEM_USER'
UNION ALL
SELECT CURRENT_USER,'CURRENT_USER'
UNION ALL
SELECT HOST_NAME(),'HOST_NAME'
UNION ALL
SELECT APP_NAME(),'APP_NAME'